/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsQueuesRouteImport } from './routes/docs/queues'
import { Route as DocsInstallationRouteImport } from './routes/docs/installation'
import { Route as DocsHttpRouteImport } from './routes/docs/http'
import { Route as DocsDependencyInjectionRouteImport } from './routes/docs/dependency-injection'
import { Route as DocsConfigurationRouteImport } from './routes/docs/configuration'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsQueuesRoute = DocsQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsHttpRoute = DocsHttpRouteImport.update({
  id: '/http',
  path: '/http',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDependencyInjectionRoute = DocsDependencyInjectionRouteImport.update({
  id: '/dependency-injection',
  path: '/dependency-injection',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/dependency-injection': typeof DocsDependencyInjectionRoute
  '/docs/http': typeof DocsHttpRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/queues': typeof DocsQueuesRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/dependency-injection': typeof DocsDependencyInjectionRoute
  '/docs/http': typeof DocsHttpRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/queues': typeof DocsQueuesRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/dependency-injection': typeof DocsDependencyInjectionRoute
  '/docs/http': typeof DocsHttpRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/queues': typeof DocsQueuesRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/configuration'
    | '/docs/dependency-injection'
    | '/docs/http'
    | '/docs/installation'
    | '/docs/queues'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/configuration'
    | '/docs/dependency-injection'
    | '/docs/http'
    | '/docs/installation'
    | '/docs/queues'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/configuration'
    | '/docs/dependency-injection'
    | '/docs/http'
    | '/docs/installation'
    | '/docs/queues'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/queues': {
      id: '/docs/queues'
      path: '/queues'
      fullPath: '/docs/queues'
      preLoaderRoute: typeof DocsQueuesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/http': {
      id: '/docs/http'
      path: '/http'
      fullPath: '/docs/http'
      preLoaderRoute: typeof DocsHttpRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dependency-injection': {
      id: '/docs/dependency-injection'
      path: '/dependency-injection'
      fullPath: '/docs/dependency-injection'
      preLoaderRoute: typeof DocsDependencyInjectionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsDependencyInjectionRoute: typeof DocsDependencyInjectionRoute
  DocsHttpRoute: typeof DocsHttpRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsQueuesRoute: typeof DocsQueuesRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsDependencyInjectionRoute: DocsDependencyInjectionRoute,
  DocsHttpRoute: DocsHttpRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsQueuesRoute: DocsQueuesRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
